apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: backendconfig-example
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    type: HTTP
    requestPath: /wp-json/wp/v2/  # Ensure consistency
    port: 80
